apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2-backend
  template:
    metadata:
      labels:
        app: app2-backend
    spec:
      containers:
        - name: app2-backend
          image: app2-backend:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "dev"
---
apiVersion: v1
kind: Service
metadata:
  name: app2-backend
spec:
  type: ClusterIP
  selector:
    app: app2-backend
  ports:
    - port: 5000
      targetPort: 5000
