name: CI

on:
  push:
  pull_request:

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test APP2 (backend)
        run: |
          cd app2-backend
          bash test_api.sh

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Secret scanning (gitleaks)
        uses: gitleaks/gitleaks-action@v2

      - name: Build & Push APP2
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: ./app2-backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app2-backend:latest

      - name: Scan APP2 image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/app2-backend:latest
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH




      - name: Build & Push APP1
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: ./app1-frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app1-frontend:latest



      - name: Scan APP1 image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/app1-frontend:latest
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH
